### ISSUE TITLE
how to login  kiali-operator  kiali provided

### ISSUE THREAD

**Issue by rafilkmp3** [kiali/helm-charts#25]
I cant find a way to login on kiali created by kiali operator and i cant find a way to set `strategy="anonymous`  on operator chart

**Comment by jmazzitelli** [comment]
Docs are here: https://kiali.io/documentation/latest/installation-guide/#_create_or_edit_the_kiali_cr
To configure Kiali you edit the Kiali CR that the operator looks for.

(NOTE: for some reason, the helm-chart repo allowed "issues" to be created - we need to shut that off. All issues should be posted to the [kiali/kiali repo](https://github.com/kiali/kiali/issues). If you have more questions regarding this, I suggest you create a github "discussion" in kiali/kiali since this isn't a bug or feature request - to do that, go here: https://github.com/kiali/kiali/discussions - I'll close this issue and shutdown "issues" in the helm-chart repo since no one is monitoring this issues list)
